<main class="about">
  <div class="plx-1">
    <div class="banner">
      <h1>About</h1>
      <a href="#container"><i class="fas fa-chevron-right"></i></a>
    </div>
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
      <path fill="#31326f" fill-opacity="1"
        d="M0,224L60,186.7C120,149,240,75,360,42.7C480,11,600,21,720,48C840,75,960,117,1080,117.3C1200,117,1320,75,1380,53.3L1440,32L1440,320L1380,320C1320,320,1200,320,1080,320C960,320,840,320,720,320C600,320,480,320,360,320C240,320,120,320,60,320L0,320Z">
      </path>
    </svg>
  </div>
  <div id="container">
    <div class="title"><span>Hi ! Lorem ipsum</span><span>dolor sit amet consectetur,</span><span>adipisicing elit
        obis.</span></div>
    <section>
      <article>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Illum magnam dignissimos dolorum cupiditate
          excepturi ut suscipit eligendi libero nisi minus.</p>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Voluptates quia, non beatae necessitatibus vitae
          facilis.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus impedit quibusdam earum incidunt ipsa cum
          repellendus, maxime quas doloribus. Odit explicabo nisi, placeat nemo voluptates asperiores ea dolorem sequi
          id culpa excepturi quaerat, perspiciatis magnam soluta vel quidem mollitia enim.</p>
        <p class="readMore"><a href="travels"><i class="fas fa-long-arrow-alt-right"></i>Dive Deeper</a></p>
      </article>
      <article>
        <div class="card">
          <img src="assets/img/profile2.jpeg" alt="profile 2">
        </div>
        <div class="card">
          <img src="assets/img/profile1.jpg" alt="profile 1">
        </div>
      </article>
    </section>
    <section>Section two</section>
  </div>
</main>