<main class="accountBack">
  <h1>My account</h1>
  <h2><?=htmlspecialchars($user['rank']) ?></h2>
  <?php if (isset($_GET["errorMsg"])): ?>
  <h3><?=$_GET["errorMsg"] ?></h3>
  <?php endif; ?>
  <form action="confirmProfile" method="post">
    <h3>Personal Information</h3>
    <label class="form-label">First name</label>
    <input type="text" name="firstName" class="form-control shadow-none"
      value="<?=htmlspecialchars($user['firstName']) ?>">
    <label class="form-label">Last name</label>
    <input type="text" name="lastName" class="form-control shadow-none"
      value="<?=htmlspecialchars($user['lastName']) ?>">
    <label class="form-label">Date of Birth</label>
    <input type="date" name="dob" value="<?=htmlspecialchars($user['dob']) ?>" class="form-control shadow-none">
    <label class="form-label">Email address</label>
    <input type="email" name="email" class="form-control shadow-none" value="<?=htmlspecialchars($user['email']) ?>">
    <label class="form-label">Address</label>
    <textarea name="address" class="form-control shadow-none"><?=htmlspecialchars($user['address']) ?></textarea>
    <label class="form-label">Old password</label>
    <input type="password" name="oldPassword" class="form-control shadow-none">
    <label class="form-label">New password</label>
    <input type="password" name="newPassword" class="form-control shadow-none">
    <label class="form-label">Confirm password</label>
    <input type="password" name="confirmPassword" class="form-control shadow-none">
    <button type="submit" class="btn btn-primary shadow-none">Confirm</button>
  </form>
</main>