<main class="gallery">
  <h1>Gallery</h1>
  <section>
    <article class="filters continent-filters">
      <div class="filter" data-filter="all">All</div>
      <?php foreach ($continents as $continent): ?>
      <div class="filter" data-continent="<?= htmlspecialchars($country['continent']) ?>"
        data-filter="<?= htmlspecialchars($continent['continent']) ?>">
        <?= htmlspecialchars($continent['continent']) ?></div>
      <?php endforeach ?>
    </article>
    <br>
    <article class="filters country-filters">
      <?php foreach ($countries as $country): ?>
      <div class="filter" data-continent="<?= htmlspecialchars($country['continent']) ?>"
        data-country="<?= htmlspecialchars($photo['country']) ?>"
        data-filter="<?= htmlspecialchars($country['country']) ?>">
        <?= htmlspecialchars($country['country']) ?></div>
      <?php endforeach ?>
    </article>
  </section>

  <section class="photos-container">
    <?php foreach ($photos as $photo): ?>
    <?php if ($photo['display'] == 'show'): ?>
    <figure data-continent="<?= htmlspecialchars($photo['continent']) ?>"
      data-country="<?= htmlspecialchars($photo['country']) ?>">
      <img src="assets/img/<?=htmlspecialchars($photo['src']) ?>" alt="<?=htmlspecialchars($photo['name']) ?>">
      <figcaption>
        <h2><?=htmlspecialchars($photo['name']) ?></h2>
        <p><em><?=htmlspecialchars($photo['caption']) ?></em></p>
        <p><i class="fas fa-map-marker-alt"></i> <?=htmlspecialchars($photo['location']) ?> /
          <?=htmlspecialchars($photo['date']) ?></p>
      </figcaption>
    </figure>
    <?php endif ?>
    <?php endforeach ?>
  </section>
</main>