<main class="galleryBack container">
  <h1>Gallery</h1>

  <?php if (isset($_GET["errorMsg"])): ?>
  <h3><?=htmlspecialchars($_GET["errorMsg"]) ?></h3>
  <?php endif ?>
  <form action="uploadPhoto" method="post" enctype="multipart/form-data" class="photo-form col-6 mx-auto">
    <legend>Create a post</legend>
    <!-- <input type="file" name="img"> -->
    <input name="name" placeholder="Name" class="form-control shadow-none"></input>
    <textarea name="caption" placeholder="Caption" class="form-control shadow-none"></textarea>
    <label class="form-label">Date</label>
    <input name="date" type="date" class="form-control shadow-none"></input>

    <select class="location" name="location_id" class="shadow-none">
      <option selected disabled hidden>Choose a location</option>
      <?php foreach ($continents as $continent): ?>
      <option value="continent"><?=htmlspecialchars($continent['continent']) ?></option>
      <?php foreach ($countries as $country): ?>
      <?php if ($country['continent_id'] == $continent['id']): ?>
      <option value="country"><?=htmlspecialchars($country['country']) ?></option>
      <?php foreach ($locations as $location): ?>
      <?php if ($location['country_id'] == $country['id']): ?>
      <option value="<?=htmlspecialchars($location['id']) ?>"><?=htmlspecialchars($location['location']) ?></option>
      <?php endif ?>
      <?php endforeach ?>
      <?php endif ?>
      <?php endforeach ?>
      <?php endforeach ?>
    </select>
    <div>
      <label>New location</label>
      <br>
      <select id="continents" name="continent" class="shadow-none btn btn-secondary">
        <option selected disabled hidden>Choose a continent</option>
        <option value="new">New continent</option>
        <?php foreach ($continents as $continent): ?>
        <option data-continent="<?=htmlspecialchars($continent['continent']) ?>"
          value="<?=htmlspecialchars($continent['id']) ?>">
          <?=htmlspecialchars($continent['continent']) ?>
        </option>
        <?php endforeach ?>
      </select>
      <input id="newContinent" type="text" name="newContinent" placeholder="Continent name">
      <br>
      <select id="countries" name="country" class="shadow-none btn btn-secondary">
        <option selected disabled hidden>Choose a country</option>
        <option value="new">New country</option>
        <?php foreach ($countries as $country): ?>
        <option data-continent="<?=htmlspecialchars($country['continent']) ?>"
          value="<?=htmlspecialchars($country['id']) ?>">
          <?=htmlspecialchars($country['country']) ?>
        </option>
        <?php endforeach ?>
      </select>
      <input id="newCountry" type="text" name="newCountry" placeholder="Country name">
      <br>
      <input type="text" name="newLocation" placeholder="Location name">
    </div>

    <input type="file" name="img" class="form-control shadow-none">
    <label class="form-check-label">
      Displayed
    </label>
    <input type="hidden" name="display" value="hide">
    <input type="checkbox" name="display" value="show" class="form-check-input shadow-none">
    <br>
    <button type="submit" name="submit" class="btn btn-primary shadow-none">CONFIRM</i></button>

  </form>


  <div class="photos-container">
    <?php foreach ($photos as $photo): ?>
    <form action="confirmPhoto-id-<?=htmlspecialchars($photo['id']) ?>" method="post">

      <input type="text" name="name" value="<?=htmlspecialchars($photo['name']) ?>">
      <br>
      <img src="assets/img/<?=htmlspecialchars($photo['src']) ?>" alt="<?=htmlspecialchars($photo['name']) ?>"
        width="300">
      <br>
      <p><?=htmlspecialchars($photo['location']) ?></p>
      <input type="date" name="date" value="<?=htmlspecialchars($photo['date']) ?>">
      <textarea type="text" name="caption" cols="35" rows="5"><?=htmlspecialchars($photo['caption']) ?></textarea>
      <br>

      <div class="actions">
        <!-- <label>Show</label>
        <input type="radio" value='show' name="display" <?=($photo['display'] == 'show') ? 'checked' : '' ?>>
        <label>Hide</label>
        <input type="radio" value='hide' name="display" <?=($photo['display'] == 'hide') ? 'checked' : '' ?>> -->
        <label class="form-check-label">
          Displayed
        </label>
        <input type="hidden" name="display" value="hide">
        <input type="checkbox" name="display" value="show" class="form-check-input shadow-none"
          <?=($photo['display'] == 'show') ? 'checked' : '' ?>>
        <i class="far fa-edit"></i>
        <i class="far fa-eye-slash"></i>
        <a href="deletePhoto-id-<?=htmlspecialchars($photo['id']) ?>"><i class="far fa-trash-alt"></i></a>
        <button type="submit" name="submit"><i class="far fa-save"></i></button>
      </div>
    </form>

    <?php endforeach ?>
  </div>
</main>