<main class="home">
  <h1>Home page</h1>

  <div class="plx-1">
    <div class="plx-text">
      <span class="border">
        Parallax
      </span>
    </div>
  </div>

  <section class="section section-light">
    <h2>Section One</h2>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat, omnis! Similique et optio, unde quidem numquam
      debitis consectetur accusamus, nulla eaque iusto, dolorum fugiat odit voluptates asperiores officia voluptatibus?
      Dolor labore dolore nihil ipsum delectus voluptatem. Excepturi, facilis officiis. Voluptas esse, sapiente maxime
      omnis expedita itaque quae officia voluptates quam deleniti eos neque fugiat exercitationem asperiores quasi
      libero dicta quos magni eaque maiores vitae hic? Temporibus est velit error eveniet!</p>
  </section>

  <div class="plx-2">
    <div class="plx-text">
      <span class="border">
        Parallax
      </span>
    </div>
  </div>

  <section class="section section-dark">
    <h2>Section Two</h2>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat, omnis! Similique et optio, unde quidem numquam
      debitis consectetur accusamus, nulla eaque iusto, dolorum fugiat odit voluptates asperiores officia voluptatibus?
      Dolor labore dolore nihil ipsum delectus voluptatem. Excepturi, facilis officiis. Voluptas esse, sapiente maxime
      omnis expedita itaque quae officia voluptates quam deleniti eos neque fugiat exercitationem asperiores quasi
      libero dicta quos magni eaque maiores vitae hic? Temporibus est velit error eveniet!</p>
  </section>

  <div class="plx-3">
    <div class="plx-text">
      <span class="border">
        Parallax
      </span>
    </div>
  </div>

  <section class="section section-dark">
    <h2>Section Three</h2>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Placeat, omnis! Similique et optio, unde quidem numquam
      debitis consectetur accusamus, nulla eaque iusto, dolorum fugiat odit voluptates asperiores officia voluptatibus?
      Dolor labore dolore nihil ipsum delectus voluptatem. Excepturi, facilis officiis. Voluptas esse, sapiente maxime
      omnis expedita itaque quae officia voluptates quam deleniti eos neque fugiat exercitationem asperiores quasi
      libero dicta quos magni eaque maiores vitae hic? Temporibus est velit error eveniet!</p>
  </section>
</main>