<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <!--//*   /////////////////  -->
  <!--//!  ////JS & CDNs////  -->
  <!--//? ///////////////// -->
  <!-- Bootstrap CDN -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous" />

  <!-- jQuery.js CDN-->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
    integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg=="
    crossorigin="anonymous"></script>

  <!-- Vue.js CDN : development version, includes helpful console warnings -->
  <script src="https://unpkg.com/vue@next"></script>

  <!-- FontAwesome CDN -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"
    integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w=="
    crossorigin="anonymous" />


  <!--//*   /////////////////  -->
  <!--//!  ///////CSS///////  -->
  <!--//? ///////////////// -->
  <!-- Audiowide & Raleway Fonts -->
  <link rel="preconnect" href="https://fonts.gstatic.com" />
  <link
    href="https://fonts.googleapis.com/css2?family=Audiowide&family=Raleway:ital,wght@0,400;0,600;1,400;1,600&display=swap"
    rel="stylesheet" />
  <link rel="stylesheet" href="assets/css/normalize.css">
  <link rel="stylesheet" href="assets/css/style.css" />
  <title>Diving Nomad</title>
</head>

<body>
  <header>
    <nav class="language-nav">
      <a href=""><img src="https://www.countryflags.io/us/shiny/64.png"></a>
      <a href=""><img src="https://www.countryflags.io/fr/shiny/64.png"></a>
      <a href=""><img src="https://www.countryflags.io/cn/shiny/64.png"></a>
      <a href=""><img src="https://www.countryflags.io/es/shiny/64.png"></a>
      <a href=""><img src="https://www.countryflags.io/it/shiny/64.png"></a>
      <a href=""><img src="https://www.countryflags.io/br/shiny/64.png"></a>
    </nav>
    <?php include $this->_mainNav ?>

  </header>
  <?php include $template ?>
  <footer>
    <?php if (isset($_SESSION["user"])): ?>
    <p>Logged in as <?=$_SESSION["email"] ?>.</p>
    <?php endif; ?>
    <div class="confirmOverlay">
      <div class="confirmBox">
        <h2>Are you sure ?</h2>
        <i class="fas fa-times" id="close"></i>
        <i class="fas fa-exclamation-circle"></i>
        <p>This will permanently delete the item.</p>
        <div class="buttons">
          <button class="btn shadow-none btn-outline-secondary" id="cancel">Cancel</button>
          <button class="btn shadow-none btn-outline-danger" id="confirm">Confirm</button>
        </div>
      </div>
    </div>

    <div id="imgPickerOverlay">
      <div id="imgPickerContent">
        <div class="header">
          <i class="fas fa-times" id="close"></i>
          Choose an image
        </div>

        <div class="body">
          <?php foreach ($photos as $photo): ?>

          <figure data-id="<?= htmlspecialchars($photo['id']) ?>">
            <img src="<?= htmlspecialchars($photo['src']) ?>" alt="<?= htmlspecialchars($photo['name']) ?>">
          </figure>
          <?php endforeach ?>
        </div>
        <div class="footer">
          <a id="cancel" class="btn btn-outline-secondary fs-3 shadow-none">Cancel</a>
          <a id="confirm" class="btn btn-outline-success fs-3 shadow-none">Confirm</a>
        </div>
      </div>
    </div>
  </footer>
  <!-- <script type="module" src="assets/js/index.js" defer></script> -->
  <script src="assets/js/script.js" defer></script>

</body>

</html>