<nav class="nav nav-back">

  <li>
    <a href="about"><i class="fas fa-users"></i></a>
    About Me
    <a href="aboutBack"><i class="fas fa-user-edit"></i></a>
  </li>
  <li>

  <li>
    <a href="travels"><i class="fas fa-users"></i></a>
    Travels
    <a href="travelsBack"><i class="fas fa-user-edit"></i></a>
  </li>
  <li>
    <a href="projects"><i class="fas fa-users"></i></a>
    Projects
    <a href="projectsBack"><i class="fas fa-user-edit"></i></a>
  </li>
  <li>
    <a href="gallery"><i class="fas fa-users"></i></a>
    Gallery
    <a href="galleryBack"><i class="fas fa-user-edit"></i></a>
  </li>
  <li>
    <a href="home"><img src="assets/img/logo.jpg" alt="Logo" /></a>
  </li>
  <li>
    <a href="locations"><i class="fas fa-users"></i></a>
    Locations
    <a href="locationsBack"><i class="fas fa-user-edit"></i></a>
  </li>
  <li>
    <a href="dashboard">Dashboard</a>
  </li>
  <li>
    <a href="accountBack">My Account</a>
  </li>
  <li>
    <a href="test">Test</a>
  </li>


  <li>
    <a href="logout">Logout</a>
  </li>

  <!-- <nav class="social-nav">
    <li><a href="https://www.facebook.com/romain.tangpavillard" target="_blank"><i class="fab fa-facebook-f"></i></a>
    </li>
    <li><a href="https://www.instagram.com/rom1tp" target="_blank"><i class="fab fa-instagram"></i></a></li>
    <li><a href="mailto:romaintangpav@gmail.com" target="_blank"><i class="far fa-envelope"></i></a></li>
    <li><a href="https://github.com/rom1tp" target="_blank"><i class="fab fa-github"></i></a></li>
    <li><a href="https://www.linkedin.com/in/romain-tang" target="_blank"><i class="fab fa-linkedin-in"></i></a></li>
  </nav> -->
</nav>