<main class="post">
  <h1><?= htmlspecialchars($post['name']) ?></h1>

  <div class="plx-1"></div>

  <section>
    <h2><?= htmlspecialchars($post['title1']) ?></h2>
    <p><?= htmlspecialchars($post['text1']) ?></p>
  </section>

  <div class="plx-2"></div>

  <section>
    <h2><?= htmlspecialchars($post['title2']) ?></h2>
    <p><?= htmlspecialchars($post['text2']) ?></p>
  </section>

  <div class="plx-3"></div>
</main>