<main class="post">

  <div class="plx-1">
    <img data-src="assets/img/<?= htmlspecialchars($post['src1']) ?>">
    <h1><?= htmlspecialchars($post['name']) ?></h1>
  </div>

  <section>
    <h2><?= htmlspecialchars($post['title1']) ?></h2>
    <p><?= htmlspecialchars($post['text1']) ?></p>
  </section>

  <div class="plx-2">
    <img data-src="assets/img/<?= htmlspecialchars($post['src2']) ?>">
  </div>

  <section>
    <h2><?= htmlspecialchars($post['title2']) ?></h2>
    <p><?= htmlspecialchars($post['text2']) ?></p>
  </section>

  <div class="plx-3">
    <img data-src="assets/img/<?= htmlspecialchars($post['src3']) ?>">
  </div>
</main>