<main class="projectsBack">
  <h1>Projects</h1>
  <a href="addProject" class="btn btn-outline-primary fs-1 shadow-none">Add Project</a>

  <?php foreach ($projects as $project): ?>

  <form action="confirmProject-id-<?= htmlspecialchars($project['id']) ?>" method="post">
    <input type="text" name="name" value="<?= htmlspecialchars($project['name']) ?>">
    <br>
    <textarea name="subtitle" cols="60" rows="3"><?= htmlspecialchars($project['subtitle']) ?></textarea>
    <br>
    <textarea name="description" cols="60" rows="10"><?= htmlspecialchars($project['description']) ?></textarea>
    <br>
    <img src="<?= htmlspecialchars($project['src']) ?>" width="300">
    <br>
    <input type="text" name="url" placeholder="Url" value="<?= htmlspecialchars($project['url']) ?>">

    <label>Show</label>
    <input type="radio" value='show' name="display-<?= htmlspecialchars($project['id']) ?>"
      <?= ($project['display'] == 'show')? 'checked': '' ?>>
    <label>Hide</label>
    <input type="radio" value='hide' name="display-<?= htmlspecialchars($project['id']) ?>"
      <?= ($project['display'] == 'hide')? 'checked': '' ?>>
    <br>
    <button type="submit">Confirm</button>
  </form>
  <a class="button" href="deleteProject-id-<?= htmlspecialchars($project['id']) ?>">Delete</a>
  <?php endforeach; ?>
</main>