<main class="projects">
  <h1>Projects</h1>

  <section class="projects-container">
    <?php foreach ($projects as $project): ?>
    <?php if ($project['display'] == 'show'): ?>
    <figure>
      <img src="https://picsum.photos/1600/900" alt="<?=htmlspecialchars($project['name']) ?>">
      <!-- <img src="<?=htmlspecialchars($project['src']) ?>" alt="<?=htmlspecialchars($project['name']) ?>"> -->
      <figcaption>
        <h3><?= htmlspecialchars($project['name']) ?></h3>
        <p><?= htmlspecialchars($project['subtitle']) ?></p>
        <p><a href="<?= htmlspecialchars($project['url']) ?>">See Project</a></p>
      </figcaption>
    </figure>
    <?php endif ?>
    <?php endforeach ?>
  </section>
</main>