<main class="test">
  <h1>Test page</h1>
  <a href="#" id="openPhotoPicker" class="btn btn-primary">Choose from gallery</a>
  <div class="overlay">
    <div class="container">
      <div class="header">Header</div>
      <div class="body">
        <img src="https://picsum.photos/300/200" alt="">
        <img src="https://picsum.photos/300/200" alt="">
        <img src="https://picsum.photos/300/200" alt="">
        <img src="https://picsum.photos/300/200" alt="">
        <img src="https://picsum.photos/300/200" alt="">
        <img src="https://picsum.photos/300/200" alt="">
        <img src="https://picsum.photos/300/200" alt="">
        <img src="https://picsum.photos/300/200" alt="">
        <img src="https://picsum.photos/300/200" alt="">
        <img src="https://picsum.photos/300/200" alt="">
        <img src="https://picsum.photos/300/200" alt="">
        <img src="https://picsum.photos/300/200" alt="">
        <img src="https://picsum.photos/300/200" alt="">
        <img src="https://picsum.photos/300/200" alt="">
        <img src="https://picsum.photos/300/200" alt="">
        <img src="https://picsum.photos/300/200" alt="">
        <img src="https://picsum.photos/300/200" alt="">
        <img src="https://picsum.photos/300/200" alt="">

      </div>
      <div class="footer">Footer <button id="closePhotoPicker" class="btn btn-outline-danger shadow-none">Close</button>
      </div>
    </div>
  </div>
</main>