<main class="travelsBack">
  <h1>Travels page</h1>

  <?php if (isset($_GET["errorMsg"])) : ?>
  <h3><?= htmlspecialchars($_GET["errorMsg"]) ?></h3>
  <?php endif; ?>
  <form action="uploadPost" method="post" enctype="multipart/form-data" class="post-form col-6 mx-auto">
    <legend>Create a post</legend>
    <!-- <input type="file" name="img"> -->
    <textarea name="name" placeholder="Name" class="form-control shadow-none"></textarea>
    <textarea name="title1" placeholder="Title 1" class="form-control shadow-none"></textarea>
    <textarea name="text1" placeholder="Text 1" class="form-control shadow-none"></textarea>
    <textarea name="title2" placeholder="Title 2" class="form-control shadow-none"></textarea>
    <textarea name="text2" placeholder="Text 2" class="form-control shadow-none"></textarea>
    <input name="date" type="date" class="form-control shadow-none"></input>
    <select name="main_img_id">
      <option selected disabled hidden>Main img</option>
      <?php foreach ($photos as $photo): ?>
      <option value="<?= htmlspecialchars($photo['id']) ?>"><?= htmlspecialchars($photo['id']) ?></option>
      <?php endforeach ?>
    </select>
    <select name="img1_id">
      <option selected disabled hidden>Img 1</option>
      <?php foreach ($photos as $photo): ?>
      <option value="<?= htmlspecialchars($photo['id']) ?>"><?= htmlspecialchars($photo['id']) ?></option>
      <?php endforeach ?>
    </select>
    <select name="img2_id">
      <option selected disabled hidden>Img 2</option>
      <?php foreach ($photos as $photo): ?>
      <option value="<?= htmlspecialchars($photo['id']) ?>"><?= htmlspecialchars($photo['id']) ?></option>
      <?php endforeach ?>
    </select>
    <br>
    <button type="submit" name="submit" class="btn btn-primary shadow-none">CONFIRM</button>
  </form>

  <div class="container">
    <div class="row">
      <?php foreach ($posts as $post): ?>
      <div class="col-5 mx-auto">
        <form action="confirmPost-id-<?= htmlspecialchars($post['id']) ?>" method="post" class="post-form">
          <textarea name="name" class="form-control shadow-none"><?= htmlspecialchars($post['name']) ?></textarea>
          <textarea name="title1" class="form-control shadow-none"><?= htmlspecialchars($post['title1']) ?></textarea>
          <textarea name="text1" class="form-control shadow-none"><?= htmlspecialchars($post['text1']) ?></textarea>
          <textarea name="title2" class="form-control shadow-none"><?= htmlspecialchars($post['title2']) ?></textarea>
          <textarea name="text2" class="form-control shadow-none"><?= htmlspecialchars($post['text2']) ?></textarea>
          <img src="assets/img/<?= htmlspecialchars($post['src1']) ?>" width="200" height="150">
          <img src="assets/img/<?= htmlspecialchars($post['src2']) ?>" width="200" height="150">
          <img src="assets/img/<?= htmlspecialchars($post['src3']) ?>" width="200" height="150">
          <br>
          <input type="date" name="date" value="<?=htmlspecialchars($post['date']) ?>">
          <label>Show</label>
          <input type="radio" value='show' name="display-<?= htmlspecialchars($post['id']) ?>"
            <?= ($post['display'] == 'show')? 'checked': '' ?>>
          <label>Hide</label>
          <input type="radio" value='hide' name="display-<?= htmlspecialchars($post['id']) ?>"
            <?= ($post['display'] == 'hide')? 'checked': '' ?>>
          <br>
          <button type="submit">Confirm</button>
        </form>
        <a class="button" href="deletePost-id-<?= htmlspecialchars($post['id']) ?>">Delete</a>
      </div>
      <?php endforeach; ?>
    </div>
  </div>

</main>