<main class="travels">
  <h1>Travels page</h1>
  <div class="container">
    <?php foreach ($posts as $post): ?>
    <?php if ($post['display'] == 'show'): ?>
    <article>
      <a href="post-id-<?= htmlspecialchars($post['id']) ?>">
        <img src="assets/img/<?= htmlspecialchars($post['src1']) ?>">
      </a>
      <div class="text">
        <h2><?= htmlspecialchars($post['name']) ?></h2>
        <p><?= htmlspecialchars($post['text1']) ?></p>
      </div>
    </article>
    <?php endif; ?>
    <?php endforeach; ?>
  </div>
</main>