<main class="travelsBack">
  <h1>Travels page</h1>
  <a href="addPost" class="btn btn-outline-primary fs-1 shadow-none">Add Post</a>

  <div class="container">
    <table class="table col-8">
      <thead>
        <tr>
          <th>#</th>
          <th>Name</th>
          <th>Date</th>
          <th>Image 1</th>
          <th>Image 2</th>
          <th>Image 3</th>
          <th>Visibility</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($posts as $post): ?>
        <tr>
          <td><?= htmlspecialchars($post['id']) ?></td>
          <td><?= htmlspecialchars($post['name']) ?></td>
          <td><?= htmlspecialchars($post['date']) ?></td>
          <td><img src="<?= htmlspecialchars($post['src1']) ?>" width="80"></td>
          <td><img src="<?= htmlspecialchars($post['src2']) ?>" width="80"></td>
          <td><img src="<?= htmlspecialchars($post['src3']) ?>" width="80"></td>
          <td><?= htmlspecialchars($post['display']) ?></td>
          <td class="actions">
            <input data-id="<?= htmlspecialchars($post['id']) ?>" type="hidden" name="display" value="hide">
            <input data-id="<?= htmlspecialchars($post['id']) ?>" type="hidden" name="display" value="show"
              class="form-check-input shadow-none" <?=($post['display'] == 'show') ? 'checked' : '' ?>>
            <a href="modifyPost-id-<?= htmlspecialchars($post['id']) ?>"><i
                data-id="<?= htmlspecialchars($post['id']) ?>" class="far fa-edit"></i></a>
            <i data-id="<?= htmlspecialchars($post['id']) ?>"
              class="far fa-eye <?=($post['display'] == 'show') ? 'visible' : '' ?>"></i>
            <i data-id="<?= htmlspecialchars($post['id']) ?>"
              class="far fa-eye-slash <?=($post['display'] != 'show') ? 'visible' : '' ?>"></i>
            <a href="deletePost-id-<?=htmlspecialchars($post['id']) ?>"><i class="far fa-trash-alt"></i></a>
          </td>
        </tr>
        <?php endforeach ?>
      </tbody>
    </table>
  </div>
</main>